### PR TITLE
Added TX support

### PR DESCRIPTION
**Pull request by tmescic**
Added support for sending samples from the host to the device (TX). Tested on a Ettus x310.

### CODE REVIEW

**Comment by rhodey** [comment]
whoa, awesome! I'm away from home for the next few days but as soon as I get back to my USRP I'll try testing this. this all looks great tho :) especially the white space indenting lol, I'm picky about that. I'll probably bump the version to 0.4 with this.

**Comment by rhodey** [comment]
Sorry for the delay I promise to test this week!

**Comment by tmescic** [comment]
No problem. Take you time :)

**Comment by tmescic** [comment]
Hi. When do you plan to merge the changes? I am asking because I'm using the library in one of my projects and the build would be much simpler if the changes were merged.

**Comment by rhodey** [comment]
Hey @tmescic, I just checked out your pull locally, added two more commits for copyright & version, and pushed it to this branch https://github.com/radiowitness/uhd-java/tree/tmescic-tx_support. As soon as I get home tonight I'll test this on my hardware, should be a quick merge to master from there :)

**Comment by rhodey** [comment]
Hey @tmescic, what OS are you running and what version of UHD do you have installed? I think the UHD PPA from Ettus has updated since I last tried building from scratch, now I'm seeing...

```
$ uhd_find_devices
linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.010.000.000-release

--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    type: b100
    name: 
    serial: E8R11YEB1
```

And now both `master` and the `tmescic-tx_support` branch fail many of the tests with error message...

```
Error loading class org/anhonesteffort/uhd/usrp/MultiUsrpSharedPtr
```

I haven't spent much time debugging this yet but I guess it could be either a jar packaging issue or something about the C++ UHD API changed significantly. Either way this is certainly unrelated to your pull but I'm gonna try fixing this new issue first before merging anything else into broken master :(

**Comment by tmescic** [comment]
I am running CentOS 7. Since the UHD binary packages for CentOS were too old and did not support my device (x310), I had to compile them from source. I did this about 4 months ago.

```
$ uhd_find_devices
linux; GNU C++ version 4.8.5 20150623 (Red Hat 4.8.5-4); Boost_105300; UHD_003.010.git-202-g9e0861e1
.....
```

**Pull request closed without merging**
